"""zero_optax root module."""

from __future__ import annotations

from zero_optax.base import GradientTransformation
from zero_optax.combine import chain
from zero_optax.optimizers import adagrad, adam, adamw, lamb, lars, lion, sgd
from zero_optax import losses
from zero_optax import schedules
from zero_optax.losses import (
    squared_error,
    l2_loss,
    huber_loss,
    hinge_loss,
    perceptron_loss,
    safe_softmax_cross_entropy,
    softmax_cross_entropy,
    softmax_cross_entropy_with_integer_labels,
    sigmoid_binary_cross_entropy,
    sigmoid_focal_loss,
    multiclass_hinge_loss,
    multiclass_perceptron_loss,
    poly_loss_cross_entropy,
    ctc_loss,
    ctc_loss_with_forward_probs,
    ranking_softmax_loss,
    sparsemax_loss,
    multiclass_sparsemax_loss,
    make_fenchel_young_loss,
)
from zero_optax.schedules import (
    constant_schedule,
    join_schedules,
    warmup_constant_schedule,
    warmup_exponential_decay_schedule,
    exponential_decay,
    cosine_decay_schedule,
    warmup_cosine_decay_schedule,
    cosine_onecycle_schedule,
    piecewise_constant_schedule,
    piecewise_interpolate_schedule,
    linear_schedule,
    polynomial_schedule,
    linear_onecycle_schedule,
    inject_hyperparams,
    sgdr_schedule,
    inject_stateful_hyperparams,
)

__all__ = [
    "GradientTransformation",
    "chain",
    "losses",
    "schedules",
    "adagrad",
    "adam",
    "adamw",
    "lamb",
    "lars",
    "lion",
    "sgd",
    "squared_error",
    "l2_loss",
    "huber_loss",
    "hinge_loss",
    "perceptron_loss",
    "safe_softmax_cross_entropy",
    "softmax_cross_entropy",
    "softmax_cross_entropy_with_integer_labels",
    "sigmoid_binary_cross_entropy",
    "sigmoid_focal_loss",
    "multiclass_hinge_loss",
    "multiclass_perceptron_loss",
    "poly_loss_cross_entropy",
    "ctc_loss",
    "ctc_loss_with_forward_probs",
    "ranking_softmax_loss",
    "sparsemax_loss",
    "multiclass_sparsemax_loss",
    "make_fenchel_young_loss",
    "constant_schedule",
    "join_schedules",
    "warmup_constant_schedule",
    "warmup_exponential_decay_schedule",
    "exponential_decay",
    "cosine_decay_schedule",
    "warmup_cosine_decay_schedule",
    "cosine_onecycle_schedule",
    "piecewise_constant_schedule",
    "piecewise_interpolate_schedule",
    "linear_schedule",
    "polynomial_schedule",
    "linear_onecycle_schedule",
    "inject_hyperparams",
    "sgdr_schedule",
    "inject_stateful_hyperparams",
]
